# Generated by Django 2.2.6 on 2021-03-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('coin', models.CharField(blank=True, max_length=10)),
                ('from_address', models.CharField(blank=True, max_length=255)),
                ('to_address', models.CharField(blank=True, max_length=255)),
                ('chain_id', models.IntegerField(default=0)),
                ('tx_hash', models.CharField(blank=True, max_length=255)),
                ('create_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
