# Generated by Django 2.2.6 on 2021-03-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addy', '0002_modeltransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltransaction',
            name='chain_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
