# Generated by Django 2.2.6 on 2021-03-10 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addy', '0003_auto_20210309_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeluser',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 12, 22, 50, 863772)),
        ),
    ]
